<?php 

/**
 * Joomla! 1.5 component com_supply_order
 * Code generated by : Danny's Joomla! 1.5 MVC Component Code Generator
 * http://www.joomlafreak.be
 * date generated:
 * @version 0.8
 * @author Danny Buytaert
 * @package com_com_supply_order
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 **/

// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );


jimport('joomla.application.component.model');

class SupplyOrderRequest extends JModel
{
	private $request = array();
	
	/**
	 * Array setter 
	 * 
	 * @var int, string, float
	 */
	function setRequest($field, $value)
	{
		$this->request["$field"] = $value;
	}
	
	/**
	 * Constructor
	 *
	 * @since 1.5
	 */
	function __construct()
	{
		parent::__construct();
	}

	/**
	 * New Request insert Query
	 * 
	 * @var array
	 * @access public
	 */
	function requestInsertSql() 
	{
		$columns = "(";
		$columnValue = "(";
		foreach ($this->request as $field => $value)
		{
			$columns .= $field."'";
			$columnValue .= "\"".$value."\",";
		}
		$columns = substr($columns, 0, -1);
		$columnValue = substr($columnValue, 0, -1);
		
		$columns .= ")";
		$columnValue .= ")";
		
		$insertSql = "Insert into `#__so_order` $columns values $columnValue";
		
		$db->setQuery($insertSql);
		
		try
		{
			$db->query();
			$requestId = $db->insertid();
			return $requestId;//return true;
		}
		catch (Exception $e)
		{
			return false;
		}
	}
	
	/**
	 * Request update query
	 * 
	 * @var int record id
	 * @access public
	 * @return boolean 
	 * 
	 */
	function updateRequest($id)
	{
		$fieldValuePair = "";
		foreach ($this->request as $field => $value)
		{
			$fieldValuePair .= $field. "= \"".$value."\",";
		}
		
		$fieldValuePair = substr($fieldValuePair, 0, -1);
		$fieldValuePair = "Update `#__so_order` set $fieldValuePair where order_id = $id";
		
		$db->setQuery($fieldValuePair);
		try
		{
			$db->query();
			$requestId = $db->insertid();
			return $requestId;//return true;
		}
		catch (Exception $e)
		{
			return false;
		}
		
	}
	
	/**
	 * Request Delete query
	 * 
	 * @var int record id
	 * @access public
	 * @return boolean
	 *
	 */
	function deleteRequest($id)
	{
		$deleteQuery = "Delete From `#__so_order` where order_id = $id";
	
		$db->setQuery($deleteQuery);
		try
		{
			$db->query();
			return $db->loadResult();//return true;
		}
		catch (Exception $e)
		{
			return false;
		}
	}
	
	/**
	 * Get Status Id for the request
	 * 
	 * @var int request id
	 * @access public
	 * @return string
	 */
	function getStatusId($id)
	{
		$statusIdQuery = "Slect `order_status_id` from `#__so_order` where order_id = $id";
		$db->setQuery($statusIdQuery);
		try
		{
			return $db->loadResult();//return true;
		}
		catch (Exception $e)
		{
			return false;
		}
	}
	
	/**
	 * Update Status Id for the request
	 *
	 * @var int list or single request id
	 * @access public
	 * @return string
	 */
	function updateStatus($id, $statusId)
	{
		
	}
	
	/**
	 * List request by owner
	 * 
	 * @var string email
	 * @access public
	 * @return array
	 *  
	 */
	function listRequestByOwner($employeId)
	{
		
	}
	
}