<?php 

/**
 * Joomla! 1.5 component com_supply_order
 * Code generated by : Danny's Joomla! 1.5 MVC Component Code Generator
 * http://www.joomlafreak.be
 * date generated:  
 * @version 0.8
 * @author Danny Buytaert 
 * @package com_com_supply_order
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 **/

// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );


function com_uninstall()
  {
  ?>
<div class="header">Com_supply_order is sucessfully removed </div>
<p>
  Bye.
</p>
<?php
  }
?>