<?php 

/**
 * Joomla! 1.5 component com_supply_order
 * Code generated by : Danny's Joomla! 1.5 MVC Component Code Generator
 * http://www.joomlafreak.be
 * date generated:  
 * @version 0.8
 * @author Danny Buytaert 
 * @package com_com_supply_order
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 **/

// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );


  /**
  * @package com_supply_order
  */
  class Com_supply_orderHelper
{
function checkCategories() {
  global $mainframe ;
  $db =& JFactory::getDBO();
  $db->setQuery( "SELECT * FROM #__categories WHERE `section`='com_com_supply_order'" ) ;
  $rows = $db->loadAssocList() ;
  if(empty($rows)) {
 $mainframe->enqueueMessage( JText::_( 'You have no categories configured yet' ), 'notice' ) ;
  return false ;
  }
  return true ;
  }
  }